// <auto-generated />
using FinalProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(OdevContext))]
    partial class OdevContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Ogrenciler", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SinifID")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciID");

                    b.HasIndex("SinifID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("FinalProject.tblDersler", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersID"));

                    b.Property<string>("DersAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DersID");

                    b.ToTable("tblDersler");

                    b.HasData(
                        new
                        {
                            DersID = 1,
                            DersAd = "Nesne Tabanlı Programlama",
                            DersKod = "001"
                        },
                        new
                        {
                            DersID = 2,
                            DersAd = "Veritabanı",
                            DersKod = "002"
                        },
                        new
                        {
                            DersID = 3,
                            DersAd = "Görsel Programlama",
                            DersKod = "003"
                        },
                        new
                        {
                            DersID = 4,
                            DersAd = "Web Programlama",
                            DersKod = "004"
                        });
                });

            modelBuilder.Entity("FinalProject.tblOgrenciDers", b =>
                {
                    b.Property<int>("OgrenciID")
                        .HasColumnType("int");

                    b.Property<int>("DersID")
                        .HasColumnType("int");

                    b.HasKey("OgrenciID", "DersID");

                    b.HasIndex("DersID");

                    b.ToTable("tblOgrenciDers");
                });

            modelBuilder.Entity("FinalProject.tblSiniflar", b =>
                {
                    b.Property<int>("SinifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinifID"));

                    b.Property<int>("Kontenjan")
                        .HasColumnType("int");

                    b.Property<string>("SinifAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SinifID");

                    b.ToTable("tblSiniflar");

                    b.HasData(
                        new
                        {
                            SinifID = 1,
                            Kontenjan = 20,
                            SinifAd = "1.Sınıf"
                        },
                        new
                        {
                            SinifID = 2,
                            Kontenjan = 20,
                            SinifAd = "2.Sınıf"
                        },
                        new
                        {
                            SinifID = 3,
                            Kontenjan = 20,
                            SinifAd = "3.Sınıf"
                        },
                        new
                        {
                            SinifID = 4,
                            Kontenjan = 20,
                            SinifAd = "4.Sınıf"
                        });
                });

            modelBuilder.Entity("FinalProject.Ogrenciler", b =>
                {
                    b.HasOne("FinalProject.tblSiniflar", "Sinif")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("SinifID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("FinalProject.tblOgrenciDers", b =>
                {
                    b.HasOne("FinalProject.tblDersler", "Ders")
                        .WithMany("tblOgrenciDers")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Ogrenciler", "Ogrenci")
                        .WithMany("tblOgrenciDers")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("FinalProject.Ogrenciler", b =>
                {
                    b.Navigation("tblOgrenciDers");
                });

            modelBuilder.Entity("FinalProject.tblDersler", b =>
                {
                    b.Navigation("tblOgrenciDers");
                });

            modelBuilder.Entity("FinalProject.tblSiniflar", b =>
                {
                    b.Navigation("Ogrenciler");
                });
#pragma warning restore 612, 618
        }
    }
}
